apiVersion: v1
kind: ConfigMap
metadata:
  name: grade-inquiry-config
  namespace: grade-inquiry
data:
  # 애플리케이션 설정
  SPRING_PROFILES_ACTIVE: "nks"
  
  # 데이터베이스 설정
  MYSQL_DATABASE: "grade_portal"
  MYSQL_MASTER_PORT: "3306"
  MYSQL_SLAVE_PORT: "3306"
  
  # Redis 설정
  REDIS_PORT: "6379"
  
  # JVM 설정
  JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=200"